### PR TITLE
Blockdiagonal factorizations refactor

### LINKED ISSUE #162: [BUG] SVD of rectangular block structure
```julia
using BlockArrays
using BlockSparseArrays
using BlockSparseArrays: blocksparse
using MatrixAlgebraKit

ax = (blockedrange([2, 2]), blockedrange([2, 2, 2]))
bs = Dict(
  Block(1, 1) => randn(2, 2),
  Block(2, 3) => randn(2, 2),
)
a = blocksparse(bs, ax)
u, s, v = svd_compact(a)
```
returns:
```julia
ERROR: LoadError: BoundsError: attempt to access 2-element Vector{Base.OneTo{Int64}} at index [3]
Stacktrace:
  [1] throw_boundserror(A::Vector{Base.OneTo{Int64}}, I::Tuple{Int64})
    @ Base ./essentials.jl:14
  [2] setindex!
    @ ./array.jl:986 [inlined]
  [3] initialize_output(::typeof(svd_compact!), A::BlockSparseMatrix{…}, alg::BlockSparseArrays.BlockPermutedDiagonalAlgorithm{…})
    @ BlockSparseArrays ~/.julia/dev/BlockSparseArrays/src/factorizations/svd.jl:65
  [4] svd_compact!
    @ ~/.julia/packages/MatrixAlgebraKit/Yrs13/src/algorithms.jl:189 [inlined]
  [5] #svd_compact!#67
    @ ~/.julia/packages/MatrixAlgebraKit/Yrs13/src/algorithms.jl:183 [inlined]
  [6] svd_compact!
    @ ~/.julia/packages/MatrixAlgebraKit/Yrs13/src/algorithms.jl:182 [inlined]
  [7] svd_compact(A::BlockSparseMatrix{Float64, Matrix{…}, SparseArraysBase.SparseMatrixDOK{…}, Tuple{…}})
    @ MatrixAlgebraKit ~/.julia/packages/MatrixAlgebraKit/Yrs13/src/algorithms.jl:178
  [8] top-level scope
    @ ~/.julia/dev/BlockSparseArrays/dev/rectangular_svd_bug.jl:12
  [9] include(fname::String)
    @ Main ./sysimg.jl:38
 [10] top-level scope
    @ REPL[8]:1
 [11] top-level scope
    @ none:1
in expression starting at /Users/mfishman/.julia/dev/BlockSparseArrays/dev/rectangular_svd_bug.jl:12
Some type information was truncated. Use `show(err)` to see complete types.
```

The error is thrown at this line: https://github.com/ITensor/BlockSparseArrays.jl/blob/83ed4366e3a6320af0d1ef8e687a997f43ab8794/src/factorizations/svd.jl#L65. We have to think more carefully about which blocks should get set when the block structure is rectangular.

### PR DESCRIPTION
**Pull request by lkdvos**
This PR is the start of the refactor required to implement the factorizations by first mapping from blockpermuteddiagonal to blockdiagonal, and then implementing the factorization.

In order to make this work I changed some things around:

I created a second algorithm type: `BlockDiagonalAlgorithm` and `BlockPermutedDiagonalAlgorithm` now both exist.
The latter simply permutes, then calls the implementation of the former, and then permutes back.

This approach seems quite elegant and works quite nice, but as a consequence I didn't really figure out how to deal with pre-allocating any output. Therefore now the `BlockPermutedDiagonal` simply ignores the initialized output, and it is the `BlockDiagonalAlgorithm` that really does something in `initialize_output`.

I also went a bit back and forth between wanting to pre-allocate the blocks for U and V for the missing rows/cols or not. It seems that this doesn't really make a big difference, and not doing so definitely simplifies the code a bit so this might be reasonable.

Given this, it might even be reasonable to simply avoid filling up the blocks at all: we could just call `svd_*!(@view(A[]), alg)` and let the allocation be handled by lower level functions. Given that we currently are not really in a spot to really reuse the memory, and the change with the two algorithms more or less prevents us from really providing output arrays, this could be a reasonable change as well.

I'd appreciate some feedback before I push this through to the other factorizations as well!

Fixes #162 and is a replacement of #164

### CODE REVIEW

File: src/factorizations/utility.jl [hunk 1]
```diff
@@ -0,0 +1,103 @@
...
+    throw(ArgumentError("input contains more than one block per column"))
+
+  # post-process empty rows and columns: this pairs them up in order of occurance,
+  # putting empty rows and columns due to rectangularity at the end
+  emptyrows = setdiff(Block.(1:blocksize(A, 1)), rowperm)
+  append!(rowperm, emptyrows)
+  emptycols = setdiff(Block.(1:blocksize(A, 2)), colperm)
+  append!(colperm, emptycols)
+
+  return A[rowperm, colperm], rowperm, colperm
```
Comment (mtfishman) [inline src/factorizations/utility.jl:43]:
```suggestion
  return A[rowperm, colperm], (rowperm, colperm)
```
This is mostly aesthetic, but I would be in favor of grouping the permutations together.

**Review by mtfishman — APPROVED** [review]

**Comment by mtfishman** [comment]
Looks great, thanks! This is definitely a nicer design and will be easier to customize.
