### PR TITLE
Fix splitdims(::BlockSparseArrays)

### LINKED ISSUE #50: [BUG] splitdims(::BlockSparseArrays, ::Tuple{AbstractGradedUnitRanges) result is wrong
Still investigating https://github.com/ITensor/TensorAlgebra.jl/pull/29

There is something wrong with `splitdims`, with a mix-up between `tensor_product` and `fusion_product`. The issue is around

`BlockSparseArrays.jl/ext/BlockSparseArraysTensorAlgebraExt/BlockSparseArraysTensorAlgebraExt.jl:88`
```julia
function TensorAlgebra.splitdims(
  ::SectorFusion, a::AbstractArray, split_axes::AbstractUnitRange...
)
```

I currently believe `TensorAlgebra` is fine and the test in https://github.com/ITensor/TensorAlgebra.jl/pull/29 should pass on the issue here has been fixed.

### PR DESCRIPTION
**Pull request by ogauthe**
Fixes #50

Non blocksorted axes were used to index an array whose axes are blocksorted. Therefore the intermediary arrays carries invalid blocks. This is a quickfix that returns the correct result, but the code can be improved.

### CODE REVIEW

**Comment by ogauthe** [comment]
A few comments:

- Here, we end up doing the same operations as in `GradedUnitRanges.blockmergesort` with similar code. I also do not like having to rely on `GradedUnitRanges` implementation details here. I think we could avoid both code duplication and dealing with internals by defining `GradedUnitRanges.blockpermute(a::AbstractBlockedUnitRange, indices::AbstractVector{<:Block{1}})` to return a range with permuted blocks.
- Currently `splitdims` uses a flat tuple of axes and check lengths to block it. We may replace this logic with a `BlockedTuple` of ranges.
- as mentioned in the comments, we should only use views of the blocks instead of copying. A naive `a_unblocked = @view a[sorted_axes...]` still errors.

File: ext/BlockSparseArraysTensorAlgebraExt/BlockSparseArraysTensorAlgebraExt.jl [hunk 1]
```diff
@@ -94,13 +94,17 @@ function TensorAlgebra.splitdims(
     groupreducewhile(tensor_product, split_axes, ndims(a); init=OneToOne()) do i, axis
       return length(axis) ≤ length(axes(a, i))
     end
-  blockperms = invblockperm.(blocksortperm.(axes_prod))
+  blockperms = blocksortperm.(axes_prod)
+  sorted_axes = ntuple(
+    i -> gradedrange(map(b -> length(axes_prod[i][b]), blockperms[i])), ndims(a)
+  )
```
Comment (mtfishman) [inline ext/BlockSparseArraysTensorAlgebraExt/BlockSparseArraysTensorAlgebraExt.jl:100]:
```suggestion
map((r, I) -> r[I], axes_prod, blockperms)
```
Does that do the same thing? You should be able to index a `GradedUnitRange` by a `Vector{<:Block{1}}` to do a block permutation.

Comment (mtfishman) [reply ext/BlockSparseArraysTensorAlgebraExt/BlockSparseArraysTensorAlgebraExt.jl:100]: Ah, I got a bit confused, I think it would be:
```suggestion
  sorted_axes = map((r, I) -> only(axes(r[I])), axes_prod, blockperms)
```
i.e.:
```julia
julia> using BlockArrays, GradedUnitRanges, SymmetrySectors

julia> r = gradedrange([U1(0) => 2, U1(1) => 3])
GradedUnitRanges.GradedOneTo{LabelledNumbers.LabelledInteger{Int64, U1{Int64}}, Vector{LabelledNumbers.LabelledInteger{Int64, U1{Int64}}}}
U(1)[0] => 1:2
U(1)[1] => 3:5

julia> r[[Block(2), Block(1)]]
2-blocked 5-element BlockVector{LabelledNumbers.LabelledInteger{Int64, U1{Int64}}, Vector{LabelledNumbers.LabelledUnitRange{Int64, UnitRange{Int64}, U1{Int64}}}, Tuple{GradedUnitRanges.GradedOneTo{LabelledNumbers.LabelledInteger{Int64, U1{Int64}}, Vector{LabelledNumbers.LabelledInteger{Int64, U1{Int64}}}}}}:
 LabelledNumbers.LabelledInteger{Int64, U1{Int64}}(3, U(1)[1])
 LabelledNumbers.LabelledInteger{Int64, U1{Int64}}(4, U(1)[1])
 LabelledNumbers.LabelledInteger{Int64, U1{Int64}}(5, U(1)[1])
 ─────────────────────────────────────────────────────────────
 LabelledNumbers.LabelledInteger{Int64, U1{Int64}}(1, U(1)[0])
 LabelledNumbers.LabelledInteger{Int64, U1{Int64}}(2, U(1)[0])

julia> only(axes(r[[Block(2), Block(1)]]))
GradedUnitRanges.GradedOneTo{LabelledNumbers.LabelledInteger{Int64, U1{Int64}}, Vector{LabelledNumbers.LabelledInteger{Int64, U1{Int64}}}}
U(1)[1] => 1:3
U(1)[0] => 4:5
```
Not sure if that is better than what you wrote, though what you wrote could be simplified a bit to:
```suggestion
  sorted_axes = map((r, I) -> gradedrange(length.(blocks(r[I]))), axes_prod, blockperms)
```
(ideally we could use `blocklengths` for that but that isn't defined for `BlockVector` right now).

Comment (mtfishman) [reply ext/BlockSparseArraysTensorAlgebraExt/BlockSparseArraysTensorAlgebraExt.jl:100]: Since we plan to no longer attach the sector information to the block lengths, probably this version is better:
```suggestion
  sorted_axes = map((r, I) -> only(axes(r[I])), axes_prod, blockperms)
```
since it is more "future proof".

**Comment by mtfishman** [comment]
Thanks for investigating this and finding a fix! I guess basically it was using the inverse of the correct permutation? That would explain why it didn't come up yet, since for simpler permutations the permutation and its inverse are the same.

> * Here, we end up doing the same operations as in `GradedUnitRanges.blockmergesort` with similar code. I also do not like having to rely on `GradedUnitRanges` implementation details here. I think we could avoid both code duplication and dealing with internals by defining `GradedUnitRanges.blockpermute(a::AbstractBlockedUnitRange, indices::AbstractVector{<:Block{1}})` to return a range with permuted blocks.

I think it could be reasonable to make functionality like:

- `GradedUnitRanges.blockmergesortperm`
- `GradedUnitRanges.blockmergesort`
- `GradedUnitRanges.blocksortperm`
- `GradedUnitRanges.blocksort` (not defined yet but probably should be).

part of the public interface of GradedUnitRanges.jl, since sorting by sector and merging common sectors is a pretty common operation. However, maybe they should be renamed to:

- `GradedUnitRanges.sectormergesortperm`
- `GradedUnitRanges.sectormergesort`
- `GradedUnitRanges.sectorsortperm`
- `GradedUnitRanges.sectorsort`

to make it clearer that the sorting/merging is done by sector. I don't think there is a need for `GradedUnitRanges.blockpermute(a::AbstractBlockedUnitRange, indices::AbstractVector{<:Block{1}})` since if I understand what you mean by that, that is already defined through indexing syntax like `a[indices]`, or to get it as a new axis you can do `only(axes(a[indices]))` as I suggest in the comment above.

> * Currently `splitdims` uses a flat tuple of axes and check lengths to block it. We may replace this logic with a `BlockedTuple` of ranges.

I think that makes sense, that should make the logic clearer.

> * as mentioned in the comments, we should only use views of the blocks instead of copying. A naive `a_unblocked = @view a[sorted_axes...]` still errors.

Agreed.

> * we should have explicit test for `fusedims` and `splitdims` to check these tricky cases before they appear buried in `contract`. I think they should be here in `BlockSparseArrays`.

Agreed, I see a test of `fusedims`/`splitdims` here: https://github.com/ITensor/BlockSparseArrays.jl/blob/711dc433a044bbe8f5c5a6a56ea5510d28e70192/test/test_gradedunitrangesext.jl#L89-L110 but I guess it was too simple to catch this issue.

**Comment by ogauthe** [comment]
> I guess basically it was using the inverse of the correct permutation? That would explain why it didn't come up yet, since for simpler permutations the permutation and its inverse are the same.
It was using permuted axes to read the input array, instead of reading with no permutation, then permute to write. It does not show put for trivial permutation indeed.
