### PR TITLE
Fix printing higher dimensional block sparse arrays

### LINKED ISSUE #73: [BUG] display of 3D `BlockSparseArray` errors
```julia
r = blockedrange([1])
a = BlockSparseArray{Float64}(undef,r,r,r);
display(a)
```
```julia
1×1×1-blocked 1×1×1 BlockSparseArray{Float64, 3, Array{Float64, 3}, …, …}:
[:, :, 1] =
 ERROR: TypeError: in SparseSubArrayBlocks, in BlockType, expected BlockType<:AbstractMatrix{Float64}, got Type{Array{Float64, 3}}
Stacktrace:
  [1] call(::BlockSparseArrays.BlockSparseArrayInterface, ::typeof(blocks), a::SubArray{Float64, 2, BlockSparseArray{…}, Tuple{…}, false})
    @ BlockSparseArrays ~/.julia/packages/BlockSparseArrays/7xJ0V/src/blocksparsearrayinterface/blocksparsearrayinterface.jl:341
  [2] (::DerivableInterfaces.InterfaceFunction{…})(args::SubArray{…}; kwargs::@Kwargs{})
    @ DerivableInterfaces ~/.julia/packages/DerivableInterfaces/Vk7kH/src/interface_function.jl:17
  [3] blocks(a::SubArray{Float64, 2, BlockSparseArray{…}, Tuple{…}, false})
    @ BlockSparseArrays ~/.julia/packages/BlockSparseArrays/7xJ0V/src/abstractblocksparsearray/wrappedabstractblocksparsearray.jl:72
  [4] isstored(::SubArray{Float64, 2, BlockSparseArray{…}, Tuple{…}, false}, ::Int64, ::Int64)
    @ BlockSparseArrays ~/.julia/packages/BlockSparseArrays/7xJ0V/src/abstractblocksparsearray/wrappedabstractblocksparsearray.jl:344
  [5] replace_in_print_matrix(A::SubArray{Float64, 2, BlockSparseArray{…}, Tuple{…}, false}, i::Int64, j::Int64, s::String)
    @ BlockSparseArrays ~/.julia/packages/BlockSparseArrays/7xJ0V/src/abstractblocksparsearray/wrappedabstractblocksparsearray.jl:351
  [6] print_matrix_row(io::IOContext{…}, X::AbstractVecOrMat, A::Vector{…}, i::Int64, cols::Vector{…}, sep::String, idxlast::Int64)
    @ Base ./arrayshow.jl:120
  [7] _print_matrix(io::IOContext{…}, X::AbstractVecOrMat, pre::String, sep::String, post::String, hdots::String, vdots::String, ddots::String, hmod::Int64, vmod::Int64, rowsA::UnitRange{…}, colsA::UnitRange{…})
    @ Base ./arrayshow.jl:213
  [8] print_matrix(io::IOContext{…}, X::SubArray{…}, pre::String, sep::String, post::String, hdots::String, vdots::String, ddots::String, hmod::Int64, vmod::Int64)
    @ Base ./arrayshow.jl:171
  [9] _show_nd(io::IOContext{…}, a::AbstractArray, print_matrix::typeof(Base.print_matrix), show_full::Bool, axs::Tuple{…})
    @ Base ./arrayshow.jl:322
 [10] show_nd(io::IOContext{…}, a::BlockSparseArray{…}, print_matrix::Function, show_full::Bool)
    @ Base ./arrayshow.jl:277
 [11] print_array
    @ ./arrayshow.jl:359 [inlined]
 [12] macro expansion
    @ ~/.julia/packages/GPUArraysCore/aNaXo/src/GPUArraysCore.jl:206 [inlined]
 [13] print_array(io::IOContext{Base.TTY}, X::BlockSparseArray{Float64, 3, Array{…}, SparseArraysBase.SparseArrayDOK{…}, Tuple{…}})
    @ BlockSparseArrays ~/.julia/packages/BlockSparseArrays/7xJ0V/src/abstractblocksparsearray/wrappedabstractblocksparsearray.jl:359
 [14] show(io::IOContext{…}, ::MIME{…}, X::BlockSparseArray{…})
    @ Base ./arrayshow.jl:399
 [15] (::OhMyREPL.var"#7#8"{REPL.REPLDisplay{REPL.LineEditREPL}, MIME{Symbol("text/plain")}, Base.RefValue{Any}})(io::IOContext{Base.TTY})
    @ OhMyREPL ~/.julia/packages/OhMyREPL/bkUhZ/src/output_prompt_overwrite.jl:23
 [16] with_repl_linfo(f::Any, repl::REPL.LineEditREPL)
    @ REPL ~/.julia/juliaup/julia-1.11.3+0.x64.linux.gnu/share/julia/stdlib/v1.11/REPL/src/REPL.jl:661
 [17] display
    @ ~/.julia/packages/OhMyREPL/bkUhZ/src/output_prompt_overwrite.jl:6 [inlined]
 [18] display
    @ ~/.julia/juliaup/julia-1.11.3+0.x64.linux.gnu/share/julia/stdlib/v1.11/REPL/src/REPL.jl:372 [inlined]
 [19] display(x::Any)
    @ Base.Multimedia ./multimedia.jl:340
 [20] top-level scope
    @ REPL[34]:1
Some type information was truncated. Use `show(err)` to see complete types.
```
Displaying any higher dimension array also fails. 0D, 1D and 2D are fine.

`BlockSparseArrays v0.3.0`

### PR DESCRIPTION
**Pull request by mtfishman**
Fixes #73.

### CODE REVIEW

File: src/abstractblocksparsearray/wrappedabstractblocksparsearray.jl [hunk 1]
```diff
@@ -338,11 +338,22 @@ function Base.Array(a::AnyAbstractBlockSparseArray)
...
-  bA = blocks(A)
-  return isstored(bA, bI.I...) && isstored(bA[bI.I...], bI.α...)
+  bI = BlockIndex(findblockindex.(axes(a), I))
+  blocks_a = blocks(a)
+  return isstored(blocks_a, bI.I...) && isstored(blocks_a[bI.I...], bI.α...)
+end
+
+# This circumvents issues passing certain kinds of SubArrays
+# to the more generic block sparse `isstored` definition,
+# such as `blocks(a)`.
```
Comment (mtfishman) [inline src/abstractblocksparsearray/wrappedabstractblocksparsearray.jl:350]:
```suggestion
# for example `blocks(a)` is broken for certain slices.
```

**Review by lkdvos — APPROVED** [review]
Looks like a clean fix to me. It might even make sense to keep that definition of `isstored` for `SubArray`, that does seem like how you would want to define that?

**Comment by mtfishman** [comment]
This is basically the same definition as [`getindex(::SubArray, I::Int...)`](https://github.com/JuliaLang/julia/blob/v1.11.3/base/subarray.jl#L317-L322) and [`isassigned(::SubArray, I::Int...)`](https://github.com/JuliaLang/julia/blob/v1.11.3/base/subarray.jl#L397-L402) so I guess this is a reasonable definition more generally.

**Comment by mtfishman** [comment]
I've moved the definition over to SparseArraysBase.jl, so this now relies on https://github.com/ITensor/SparseArraysBase.jl/pull/44 getting merged and registered.
